server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true
# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
vaadin.whitelisted-packages = com.vaadin,org.vaadin,dev.hilla,sr.we,de.f0rce.ace,com.infraleap,org.apache
sr.we.rest                     = http://localhost:9090/
spring.jpa.generate-ddl                          = false
spring.jpa.hibernate.ddl-auto                    = none


#properties for logging the sql statements with their parameters
logging.level.org.hibernate.SQL                             = DEBUG
logging.level.org.hibernate.type                            = ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder = ERROR
#logging
#logging.path=logs
logging.level.org.springframework.web                       = DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.path                                                = logs
logging.logback.rollingpolicy.total-size-cap				= 50KB
logging.logback.rollingpolicy.max-history					= 10
logging.logback.rollingpolicy.max-file-size					= 5KB
logging.logback.rollingpolicy.file-name-pattern				= ${LOG_PATH}/archived/${LOG_FILE}-%d{yyyy-MM-dd}.%i.log
logging.file.name											= dpworld-log
logging.pattern.file										= %d{yyyy-MM-dd HH:mm:ss} %p %m%n
spring.jpa.properties.javax.persistence.validation.mode=none
